logging:
  level:
    dev.markitect.liquibase: info
    liquibase: info
    liquibase.executor.jvm.[JdbcExecutor$ExecuteStatementCallback]: info

markitect:
  liquibase:
    properties:
      liquibase.sql.logLevel: info
