/*
 * Copyright 2023-2024 Markitect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.markitect.liquibase.spring.boot.autoconfigure;

import static org.assertj.core.api.Assertions.assertThat;

import dev.markitect.liquibase.spring.MarkitectSpringLiquibase;
import dev.markitect.liquibase.spring.SpringLiquibaseBeanPostProcessor;
import liquibase.Scope;
import liquibase.ScopeManager;
import liquibase.ThreadLocalScopeManager;
import liquibase.integration.spring.SpringLiquibase;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;

@ExtendWith({
  OutputCaptureExtension.class,
  MockitoExtension.class,
})
class AutoConfigurationTests {
  private final ApplicationContextRunner contextRunner =
      new ApplicationContextRunner()
          .withConfiguration(
              AutoConfigurations.of(
                  LiquibaseAutoConfiguration.class, MarkitectLiquibaseAutoConfiguration.class))
          .withPropertyValues(
              "markitect.liquibase.use-thread-local-scope-manager=true",
              "markitect.liquibase.properties.liquibase.sql.logLevel=info");

  @Mock(answer = Answers.CALLS_REAL_METHODS)
  private MockedStatic<Scope> mockedScope;

  @Captor private ArgumentCaptor<ScopeManager> scopeManagerCaptor;

  @Test
  void backsOffWithNoDataSourceBean() {
    contextRunner.run(
        context ->
            assertThat(context)
                .doesNotHaveBean(SpringLiquibaseBeanPostProcessor.class)
                .doesNotHaveBean(SpringLiquibase.class));
  }

  @Test
  void runsLiquibaseUpdate(CapturedOutput output) {
    contextRunner
        .withConfiguration(AutoConfigurations.of(DataSourceAutoConfiguration.class))
        .run(
            context ->
                assertThat(context)
                    .hasSingleBean(SpringLiquibaseBeanPostProcessor.class)
                    .hasSingleBean(SpringLiquibase.class)
                    .hasSingleBean(MarkitectSpringLiquibase.class));
    mockedScope.verify(() -> Scope.setScopeManager(scopeManagerCaptor.capture()));
    assertThat(scopeManagerCaptor.getAllValues())
        .singleElement()
        .isInstanceOf(ThreadLocalScopeManager.class);
    assertThat(output)
        .contains(
            "Initializing Liquibase scope manager",
            "Providing Spring environment to Liquibase",
            "CREATE TABLE \"USER\" ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
                + "username NVARCHAR(32) NOT NULL, "
                + "displayName NVARCHAR(255), "
                + "CONSTRAINT pk_user PRIMARY KEY (id), "
                + "CONSTRAINT uq_user__username UNIQUE (username))",
            "Update command completed successfully.");
  }
}
